# Generated by Django 3.2.6 on 2023-03-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nit', models.FloatField(blank=True, default=None, null=True)),
                ('sucursal', models.CharField(default='colina', max_length=100)),
            ],
        ),
    ]
