# Generated by Django 3.2.6 on 2023-03-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20230317_1752'),
        ('ips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ips',
            name='paciente',
            field=models.ManyToManyField(to='paciente.Paciente'),
        ),
    ]
