# Generated by Django 3.2.6 on 2023-03-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20230317_1752'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='nameDoctor',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='pacientes',
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultorio',
            field=models.CharField(default='ml-101', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='paciente',
            field=models.ManyToManyField(to='paciente.Paciente'),
        ),
    ]
