# Generated by Django 3.2.6 on 2023-03-17 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0001_initial'),
        ('doctor', '0002_auto_20230317_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='ips',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ips.ips'),
        ),
    ]
