# Generated by Django 3.2.6 on 2023-04-15 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_ips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='ips',
        ),
    ]
