# Generated by Django 3.2.6 on 2023-03-17 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaMedica',
            fields=[
                ('fechaConsulta', models.DateTimeField(auto_now_add=True)),
                ('sintoma', models.CharField(max_length=100)),
                ('sangre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='paciente.paciente')),
            ],
        ),
    ]
